title: Jheniffer Janice Gonsalves # your name (or website title) here
logo: "/images/jheni.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Neurocientista Computacional
  <br><br>
  
  <a href="https://www.linkedin.com/in/jheniffergonsalves/">LinkedIn</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
